### ISSUE TITLE
Linking fails in bytecode mode

### ISSUE THREAD

**Issue by jvillard** [rvantonder/hack-parallel#10]
When using `hack_parallel` in a project the linking step of bytecode builds complains about a missing external `hh_lutimes`.

```console
$ git clone https://github.com/rvantonder/hack-parallel-example.git
$ cd hack-parallel-example
$ dune build _build/default/src/main.bc
File "_none_", line 1:
Error: Error while linking /home/jul/.opam/ocaml-variants.4.07.1+flambda/lib/hack_parallel/utilities/utilities.cma(Utilities__Sys_utils):
The external function `hh_lutimes' is not available
```

I installed hack_parallel from opam (version 0.1.1) and am using the 4.07.1+flambda compiler. Native builds succeed.

**Comment by rvantonder** [comment]
@jvillard you can build a bytecode executable now using master, via #14. Will upstream to opam sometime this week.
