### ISSUE TITLE
Not installable via opam

### ISSUE THREAD

**Issue by nicodemus26** [rvantonder/hack-parallel#11]
Using compiler version 4.07.0 and opam version 1.2.2, I don't seem to be able to install `hack_parallel`, despite a listing on the opam package index https://opam.ocaml.org/packages/hack_parallel/

```
$ opam install hack_parallel
[ERROR] No package named hack_parallel found.
```

**Comment by rvantonder** [comment]
This is only available for opam 2, so please install opam 2 and try again (See here: https://opam.ocaml.org/doc/Install.html)

**Comment by nicodemus26** [comment]
I noticed you're the principal author of `comby` as well. I'm here from your wonderful Strangeloop 2019 talk a couple days ago! :-) Could you put this opam ^2.0.0 requirement in the install from source directions there?

**Comment by rvantonder** [comment]
Done in 4e7d870. Thanks for popping in :)
